src/Entity/Booking.php
<?php

namespace App\Entity;

use DateTime;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * @ORM\Entity(repositoryClass="App\Repository\BookingRepository")
 * @ORM\HasLifecycleCallbacks()
 */
class Booking
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\User", inversedBy="bookings")
     * @ORM\JoinColumn(nullable=false)
     */
    private $booker;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Ad", inversedBy="bookings")
     * @ORM\JoinColumn(nullable=false)
     */
    private $ad;

    /**
     * @ORM\Column(type="datetime")
     * @Assert\Date (message="Attention, la date d'arrivée n'est pas au bon format")
     * @Assert\GreaterThan("today", message="La date d'arrivée doit être ultérieur à la date d'aujourd'hui")
     */
    private $startDate;

    /**
     * @ORM\Column(type="datetime")
     * @Assert\Date (message="Attention, la date d'arrivée n'est pas au bon format")
     * @Assert\GreaterThan(propertyPath="startDate", message="Attention, la date de départ doit être superieur à la date d'arrivée")
     */
    private $endDate;

    /**
     * @ORM\Column(type="datetime")
     */
    private $createdAt;

    /**
     * @ORM\Column(type="float")
     */
    private $amount;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $comment;

    /**
     * Callback appelé à chaque fois qu'on crée une reservation.
     *
     * @ORM\PrePersist
     */
    public function prePersist()
    {
        if (empty($this->createdAt)) {
            $this->createdAt = new \DateTime();
        }

        if (empty($this->amount)) {
            //prix de l'annonce * nombre de jour du séjour
            $this->amount = $this->ad->getPrice() * $this->getDuration();
        }
    }

    public function getDuration()
    {
        $diff = $this->endDate->diff($this->startDate);

        return $diff->days;
    }

    /**
     * Vérifier si les jours choisis sont "bookable".
     *
     * @return bool
     */
    public function isBookableDates()
    {
        //Récupérer les jours déjà booké
        $notAvailableDays = $this->ad->getNotAvailableDays();

        //Récupérer les jours choisis de la réservation
        $bookingDays = $this->getDays();

        //Tableau des chaines de caractères des journées choisies pour la réservation
        $days = array_map(function ($day) {
            return $day->format('Y-m-d');
        }, $bookingDays);

        //Tableau des chaines de caractères des journées déjà bookées
        $notAvailable = array_map(function ($day) {
            return $day->format('Y-m-d');
        }, $notAvailableDays);

        foreach ($days as $day) {
            if (array_search($day, $notAvailable) !== false) {
                return false;
            }
        }

        return true;
    }

    /**
     * Récuperer un tableau des journnées qui correspondent à la réservation.
     *
     * @return array d'objet DateTime représentant les jours de la réservation
     */
    public function getDays()
    {
        $resultat = range(
            $this->getStartDate()->getTimestamp(),
                $this->getEndDate()->getTimestamp(),
                24 * 60 * 60
        );

        $days = array_map(function ($dayTimestamp) {
            return new \DateTime(date('Y-m-d', $dayTimestamp));
        }, $resultat);

        return $days;
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getBooker(): ?User
    {
        return $this->booker;
    }

    public function setBooker(?User $booker): self
    {
        $this->booker = $booker;

        return $this;
    }

    public function getAd(): ?Ad
    {
        return $this->ad;
    }

    public function setAd(?Ad $ad): self
    {
        $this->ad = $ad;

        return $this;
    }

    public function getStartDate(): ?\DateTimeInterface
    {
        return $this->startDate;
    }

    public function setStartDate(\DateTimeInterface $startDate): self
    {
        $this->startDate = $startDate;

        return $this;
    }

    public function getEndDate(): ?\DateTimeInterface
    {
        return $this->endDate;
    }

    public function setEndDate(\DateTimeInterface $endDate): self
    {
        $this->endDate = $endDate;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeInterface
    {
        return $this->createdAt;
    }

    public function setCreatedAt(\DateTimeInterface $createdAt): self
    {
        $this->createdAt = $createdAt;

        return $this;
    }

    public function getAmount(): ?float
    {
        return $this->amount;
    }

    public function setAmount(float $amount): self
    {
        $this->amount = $amount;

        return $this;
    }

    public function getComment(): ?string
    {
        return $this->comment;
    }

    public function setComment(?string $comment): self
    {
        $this->comment = $comment;

        return $this;
    }
}

src/Entity/User.php
<?php

namespace App\Entity;

use Cocur\Slugify\Slugify;
use Doctrine\ORM\Mapping as ORM;
use Doctrine\Common\Collections\Collection;
use Doctrine\Common\Collections\ArrayCollection;
use Symfony\Component\Security\Core\User\UserInterface;
use Symfony\Component\Validator\Constraints as Assert;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;

/**
 * @ORM\Entity(repositoryClass="App\Repository\UserRepository")
 * @ORM\HasLifecycleCallbacks
 * @UniqueEntity(
 *  fields={"email"},
 *  message="Cet email existe déjà, connectez-vous",
 * )
 */
class User implements UserInterface
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\NotBlank(message="Le prénom ne doit pas être vide")
     */
    private $firstName;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\NotBlank(message="Le nom ne doit pas être vide")
     */
    private $lastName;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\Email(message="Merci de renseigner un email valide")
     */
    private $email;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     * @Assert\Url(message="Merci de renseigner une URL valide")
     */
    private $picture;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $hash;

    /**
     * @Assert\EqualTo(propertyPath="hash", message="Les mots de passe sont différents")
     */
    public $passwordConfirm;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\Length(min=10, minMessage="L'introduction doit contenir au moins 10 caractères")
     */
    private $introduction;

    /**
     * @ORM\Column(type="text")
     * @Assert\Length(min=100, minMessage="La description doit contenir au moins 100 caractères")
     */
    private $description;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $slug;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Ad", mappedBy="author")
     */
    private $ads;

    /**
     * @ORM\ManyToMany(targetEntity="App\Entity\Role", mappedBy="users")
     */
    private $userRoles;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Booking", mappedBy="booker")
     */
    private $bookings;

    public function __construct()
    {
        $this->ads = new ArrayCollection();
        $this->userRoles = new ArrayCollection();
        $this->bookings = new ArrayCollection();
    }

    /**
     * Permet d'initialiser le slug.
     *
     * @ORM\PrePersist
     * @ORM\PreUpdate
     */
    public function initializeSlug()
    {
        if (empty($this->slug)) {
            $slugify = new Slugify();
            $this->slug = $slugify->slugify($this->firstName.' '.$this->lastName);
        }
    }

    public function getFullName()
    {
        return "{$this->firstName} {$this->lastName}";
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getFirstName(): ?string
    {
        return $this->firstName;
    }

    public function setFirstName(string $firstName): self
    {
        $this->firstName = $firstName;

        return $this;
    }

    public function getLastName(): ?string
    {
        return $this->lastName;
    }

    public function setLastName(string $lastName): self
    {
        $this->lastName = $lastName;

        return $this;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    public function getPicture(): ?string
    {
        return $this->picture;
    }

    public function setPicture(?string $picture): self
    {
        $this->picture = $picture;

        return $this;
    }

    public function getHash(): ?string
    {
        return $this->hash;
    }

    public function setHash(string $hash): self
    {
        $this->hash = $hash;

        return $this;
    }

    public function getIntroduction(): ?string
    {
        return $this->introduction;
    }

    public function setIntroduction(string $introduction): self
    {
        $this->introduction = $introduction;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getSlug(): ?string
    {
        return $this->slug;
    }

    public function setSlug(string $slug): self
    {
        $this->slug = $slug;

        return $this;
    }

    /**
     * @return Collection|Ad[]
     */
    public function getAds(): Collection
    {
        return $this->ads;
    }

    public function addAd(Ad $ad): self
    {
        if (!$this->ads->contains($ad)) {
            $this->ads[] = $ad;
            $ad->setAuthor($this);
        }

        return $this;
    }

    public function removeAd(Ad $ad): self
    {
        if ($this->ads->contains($ad)) {
            $this->ads->removeElement($ad);
            // set the owning side to null (unless already changed)
            if ($ad->getAuthor() === $this) {
                $ad->setAuthor(null);
            }
        }

        return $this;
    }

    /**
     * Permet de récupérer les différents Rôles.
     *
     * @return array
     */
    public function getRoles()
    {
        //je map sur la collection $userRoles pour en retirer uniquement le Title avec la fonction map()
        //ensuite transforme le résultat en tableau PHP classique avec la fonction toArray()
        $roles = $this->userRoles->map(function ($role) {
            return $role->getTitle();
        })->toArray();

        //J'ajoute le rôle User au tableau obtenu
        $roles[] = 'ROLE_USER';

        //je retourne les rôles sous format tableau classique PHP
        return $roles;
    }

    public function getPassword()
    {
        return $this->hash;
    }

    public function getSalt()
    {
    }

    public function getUsername()
    {
        return $this->email;
    }

    public function eraseCredentials()
    {
    }

    /**
     * @return Collection|Role[]
     */
    public function getUserRoles(): Collection
    {
        return $this->userRoles;
    }

    public function addUserRole(Role $userRole): self
    {
        if (!$this->userRoles->contains($userRole)) {
            $this->userRoles[] = $userRole;
            $userRole->addUser($this);
        }

        return $this;
    }

    public function removeUserRole(Role $userRole): self
    {
        if ($this->userRoles->contains($userRole)) {
            $this->userRoles->removeElement($userRole);
            $userRole->removeUser($this);
        }

        return $this;
    }

    /**
     * @return Collection|Booking[]
     */
    public function getBookings(): Collection
    {
        return $this->bookings;
    }

    public function addBooking(Booking $booking): self
    {
        if (!$this->bookings->contains($booking)) {
            $this->bookings[] = $booking;
            $booking->setBooker($this);
        }

        return $this;
    }

    public function removeBooking(Booking $booking): self
    {
        if ($this->bookings->contains($booking)) {
            $this->bookings->removeElement($booking);
            // set the owning side to null (unless already changed)
            if ($booking->getBooker() === $this) {
                $booking->setBooker(null);
            }
        }

        return $this;
    }
}

src/Form/BookingType.php
<?php

namespace App\Form;

use App\Entity\Booking;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use App\Form\DataTransformer\FrenchToDateTimeTransformer;
use Symfony\Component\Form\Extension\Core\Type\TextareaType;

class BookingType extends ApplicationType
{
    private $transformer;

    public function __construct(FrenchToDateTimeTransformer $transformer)
    {
        $this->transformer = $transformer;
    }

    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('startDate', TextType::class, $this->getConfiguration("Date d'arrivée", 'La date à laquelle vous allez arriver'))
            ->add('endDate', TextType::class, $this->getConfiguration('Date de départ', 'La date à laquelle vous allez quitter les lieux'))
            ->add('comment', TextareaType::class, $this->getConfiguration(false, 'Si vous avez un commentaire n\'hésitez pas à nous en faire part', [
                'required' => false,
            ]))
        ;
        //Pour transformer la date reçue en français en une date en anglais
        $builder->get('startDate')->addModelTransformer($this->transformer);
        $builder->get('endDate')->addModelTransformer($this->transformer);
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Booking::class,
        ]);
    }
}

src/Controller/BookingController.php
<?php

namespace App\Controller;

use App\Entity\Ad;
use App\Entity\Booking;
use App\Form\BookingType;
use Symfony\Component\HttpFoundation\Request;
use Doctrine\Common\Persistence\ObjectManager;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\IsGranted;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;

class BookingController extends AbstractController
{
    /**
     * @Route("/ads/{slug}/book", name="booking_create")
     * @IsGranted("ROLE_USER")
     *
     * @param Ad            $ad
     * @param Request       $request
     * @param ObjectManager $manager
     */
    public function book(Ad $ad, Request $request, ObjectManager $manager)
    {
        $booking = new Booking();

        $form = $this->createForm(BookingType::class, $booking);

        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $user = $this->getUser();

            $booking->setBooker($user)
                ->setAd($ad);

            //Si les dates ne sont pas disponibles, message d'erreur
            if (!$booking->isBookableDates()) {
                $this->addFlash(
                    'warning',
                    'Les dates que vous avez choisi ne sont pas libres'
                );
            } else {
                //Si tout est disponible, on enregistre en BDD
                $manager->persist($booking);
                $manager->flush();

                $this->addFlash(
                    'success',
                    'Vous reservation a bien été enregistré'
                );

                return $this->redirectToRoute('booking_show', [
                    'id' => $booking->getId(),
                ]);
            }
        }

        return $this->render('booking/book.html.twig', [
            'ad' => $ad,
            'form' => $form->createView(),
        ]);
    }

    /**
     * Permet d'afficher la page d'une reservation.
     *
     * @Route("/booking/{id}", name="booking_show")
     *
     * @param Booking $booking
     *
     * @return Response
     */
    public function show(Booking $booking)
    {
        return $this->render('booking/show.html.twig', [
            'booking' => $booking,
        ]);
    }
}

templates/booking/book.html.twig
{% extends 'base.html.twig' %}

{% block title %}Reserver l'appartement : {{ad.title}} {% endblock %}

{% block stylesheets %}
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.8.0/css/bootstrap-datepicker.min.css" />
{% endblock %}

{% block body %}

<div class="container">
    <h1>Reservation de l'appartement : {{ad.title}}</h1>
    <p>Vous êtes sur le point de réserver le bien de <strong>{{ad.author.fullName}}</strong>, dites nous tout, on s'occupe du reste !</p>

    {{form_start(form)}}
    <div class="alert alert-light">
       <h2>Quelles dates vous intéressent ?</h2>
       <div class="row">
            <div class="col">
                {{form_row(form.startDate)}}
            </div>
            <div class="col">
                {{form_row(form.endDate)}}
            </div>
       </div>
        <h4>Montant du séjour : <span id="amount">0</span> &euro;</h4>
        <span id="days">0</span> nuit(s) à {{ad.price}} &euro; / nuit

        <h4 class="mt-3">Vous avez un commentaire ?</h4>
        {{form_row(form.comment)}}
        <button type="submit" class="btn btn-success">Je réserve !</button>
        {{form_end(form)}}
    </div>
</div>
{% endblock %}

{% block javascripts %}
<script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.8.0/js/bootstrap-datepicker.min.js"></script>

<script>
    $(document).ready(function(){
        $('#booking_startDate, #booking_endDate').datepicker({
            format: 'dd/mm/yyyy',
            datesDisabled: [
                {% for day in ad.notAvailableDays %}
                    "{{day.format('d/m/Y')}}",
                {% endfor %}
            ],
            startDate: new Date(),
        });

        $('#booking_startDate, #booking_endDate').on('change', calculateAmount);
    });

    function calculateAmount(){

        //il faut transformer la date au format français au format international
        //18/09/2018 donne en expression régulière :
        // (\d+)\/(\d+)\/(\d{4})
        // les parenthèse c'est pour "capturer"
        // les $3-$2-$1 represente l'ordre (met le chiffre de la troisième position ici, celui de la 2ème ici et celui de la 1ère ici)
        const endDate = new Date($('#booking_endDate').val().replace(/(\d+)\/(\d+)\/(\d{4})/, '$3-$2-$1'));
        const startDate = new Date($('#booking_startDate').val().replace(/(\d+)\/(\d+)\/(\d{4})/, '$3-$2-$1'));
        
        if(startDate && endDate && startDate < endDate){
            const DAY_TIME = 24 * 60 * 60 * 1000;
            const interval = endDate.getTime() - startDate.getTime();
            const days = interval / DAY_TIME;

            const amount = days * {{ad.price}};

            $('#days').text(days);
            $('#amount').text(amount.toLocaleString('fr-FR'));
        }
    }
</script>
{% endblock %}

templates/booking/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Votre réservation N° {{booking.id}} {% endblock %}

{% block body %}

{% set ad = booking.ad %}
{% set author = ad.author %}

<div class="container">
    <h1>Votre réservation N° {{booking.id}}</h1>
    <div class="row">
        <div class="col">
            <div class="alert alert-light">
                <h2>Détails</h2>
                <dl class="row">
                    <dt class="col-md-4">Numéro</dt>
                    <dd class="col-md-8">{{booking.id}}</dd>
                    <dt class="col-md-4">Date d'arrivée</dt>
                    <dd class="col-md-8">{{booking.startDate | date('d/m/Y')}}</dd>
                    <dt class="col-md-4">Date de départ</dt>
                    <dd class="col-md-8">{{booking.endDate | date('d/m/Y')}}</dd>
                    <dt class="col-md-4">Nombre de nuits</dt>
                    <dd class="col-md-8">{{booking.duration}}</dd>
                    <dt class="col-md-4">Montant total</dt>
                    <dd class="col-md-8">{{booking.amount}} &euro;</dd>
                    <dt class="col-md-4">Votre commentaire</dt>
                    <dd class="col-md-8">{{booking.comment}}</dd>
                </dl>
                <hr>
                <h2 class="alert-heading">Votre hôte</h2>
                <div class="row mb-3">
                    <div class="col-3">
                        <img src="{{author.picture}}" class="avatar avatar-medium" alt="Image de {{author.fullName}}">
                    </div>
                    <div class="col-9">
                        <h4>
                            <a href="{{path('user_show', {'slug' : author.slug})}}">{{author.fullName}}</a>
                        </h4>
                        <span class="badge badge-primary">{{author.ads | length}} annonces</span>
                    </div>
                </div>
                {{author.description | raw}}
                <a href="{{path('user_show', {'slug' : author.slug})}}" class="btn btn-secondary">Plus d'infos sur {{author.firstName}}</a>
            </div>
        </div>
        <div class="col">
            <div class="alert alert-light">
                <h2 class="lalert-heading">Votre hébergement</h2>
                <h4>
                    <a href="{{path('ads_show', {'slug': ad.slug})}}">{{ad.title}}</a>
                </h4>
                <img src="{{ad.coverImage}}" alt="Image de {{ad.title}}" class="img-fluid">
                {{ad.contenu | raw}}

                <a href="{{path('ads_show', {'slug' : ad.slug})}}" class="btn btn-secondary">Plus d'information</a>
            </div>
        </div>
    </div>
</div>
{% endblock %}